version: '3.8'
services:
  postgres:
    image: postgres:latest
    hostname: "postgres"
    ports:
      - "6432:6432"
    environment:
      POSTGRES_USER: "cnrprod1725725750-team-77090"
      POSTGRES_PASSWORD: "cnrprod1725725750-team-77090"
      POSTGRES_DB: "cnrprod1725725750-team-77090"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: -p 6432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      SERVER_ADDRESS: "0.0.0.0:8080"
      POSTGRES_CONN: "postgres://cnrprod1725725750-team-77090:cnrprod1725725750-team-77090@postgres:6432/cnrprod1725725750-team-77090"
      POSTGRES_JDBC_URL: "jdbc:postgresql://postgres:6432/cnrprod1725725750-team-77090"
      POSTGRES_USERNAME: "cnrprod1725725750-team-77090"
      POSTGRES_PASSWORD: "cnrprod1725725750-team-77090"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "6432"
      POSTGRES_DATABASE: "cnrprod1725725750-team-77090"
    ports:
      - "8080:8080"
    command: /bin/sh -c "sleep 3 && ./app"

volumes:
  postgres_data:
